### ISSUE TITLE
How to modify src to support updating of other EXIF data types?

### ISSUE THREAD

**Issue by fxbisto** [mattwilson1024/google-photos-exif#10]
Hi Matt,

Thanks for sharing your code, I think this is going to be a lot more helpful across the globe in the coming years as people are starting to reclaim data back from the big 'G.'
My Takeout didn't have any date issues, but rather geotagging info is missing from the EXIFs. I imported 100GB's of photos into my Debian server before realising this was the case but with your code I can easily run yarn and set up a task to fix the photos (again, thanks!)
All the JSONs have the required info:

```
  "geoData": {
    "latitude": *0.6*********************,
    "longitude": 0.2***********************,
    "altitude": 100.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": *0.6*********************,
    "longitude": 0.2***********************,
    "altitude": 100.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
```
I would class myself as a light/casual coder (mainly C++ & Arduino) but am not familiar with the language used for this project - hoping someone can point me in the right direction to add in support for the location data to the necessary .ts files because there's no way I'm manually typing it for over 40,000 files ;)

Cheers

**Comment by mattwilson1024** [comment]
Hi @fxbisto, sorry for taking so long to get back to you. I'm pleased to hear that the project is potentially useful for you and others.

Geotagging data wasn't a requirement for me so I'm not sure exactly which EXIF fields you'd need to set, but if it helps here are some pointers for the main areas of the code that could be adjusted to fit your needs:

1. [src/helpers/read-photo-taken-time-from-google-json.ts](https://github.com/mattwilson1024/google-photos-exif/blob/master/src/helpers/read-photo-taken-time-from-google-json.ts) has a function called `readPhotoTakenTimeFromGoogleJson` which reads the JSON file and returns the timestamp within. I've already defined a type which includes the various fields included in the JSON file, so this function could be fairly easily tweaked to return an object containing the properties you're interested in rather than just extracting the timestamp property.

2. That function is called from [index.ts](https://github.com/mattwilson1024/google-photos-exif/blob/master/src/index.ts#L101) in the `processMediaFiles` function. Given the object from step 1 you could look to make sure that one or more geolocation values were found and if they were, pass them into `updateExifMetadata` instead of (or as well as) the `photoTimeTaken` parameter

3. The `updateExifMetadata` function in [src/helpers/update-exif-metadata.ts](https://github.com/mattwilson1024/google-photos-exif/blob/master/src/helpers/update-exif-metadata.ts#L12) is where the metadata writing magic happens. Assuming the values you need have been passed into this function (from step 2) you could set the appropriate fields inside the call to `exiftool.write(...)`. 

To figure out which field(s) you'd need to write, you could use a combination of the following:
- the TypeScript autocompletion for that call to `exiftool.write()` (for example, if you're using VSCode or similar, put your cursor after `DateTimeOriginal: timeTaken` and press Ctrl+Space to see a list of the possible properties, which comes from the TypeScript definitions bundled with the ExifTool library
- the documentation for the [ExifTool](https://exiftool.org/) library which is used by this project to actually write the metadata. The ExifTool website looks like it includes lots of detailed information about the spec
- Googling in general for the specification for the various metadata fields on images

Hope this helps :)
