### ISSUE TITLE
Installation / requirements

### ISSUE THREAD

**Issue by abaleato** [mattwilson1024/google-photos-exif#14]
Hi!

First of all, thank you for making your tool available. I think this could be very useful to a lot of people!

This is very basic, but could you perhaps briefly explain how to install the code? I have no experience with Javascript or yarn (I do with Python and its package managers), so I'd really appreciate some guidance.

Thanks!

**Comment by mattwilson1024** [comment]
Hi @abaleato, thanks - I hope the tool proves useful to you and others.

You'll first need to install Node. Depending on your platform and preferred way of installing things, you can either download and run an installer from [the Node website](https://nodejs.org/en/download/), or use a package manager. Personally I like to install it using `brew` (I use a Mac). Google will have plenty of articles to help you get Node set up on your platform.

Once you've done that, clone the repo for this project (or download it) and then you'll need to install the project dependencies, which you can do using either NPM or yarn (either should work fine). This is similar to using `pip` to install Python dependencies.

NPM usually gets installed alongside Node so is probably the most straightforward. To do that, open a terminal in the folder for this repo and run `npm install` to pull the dependencies and then run the app using something like `npm start --inputDir ~/takeout --outputDir ~/output --errorDir ~/error` (before you do this, create empty dirs for output and error and change the input argument to point to the folder where your Google takeout files are stored). See the readme for details on the input arguments.

Alternatively, you can use Yarn instead of NPM. Both will work fine for this tool, so it's just a matter of preference which one you choose. If you want to use yarn, you can install it using NPM (see https://yarnpkg.com/getting-started/install) and once you've done that the steps are very similar. First run `yarn` to install the dependencies, then `yarn start <options>` to run the app. 

Hope this helps.

**Comment by abaleato** [comment]
Excellent. This is really helpful. Thank you so much!
