### ISSUE TITLE
Error when editing photos

### ISSUE THREAD

**Issue by EdisonJwa** [mattwilson1024/google-photos-exif#3]
Error: Error reading OtherImageStart data in ExifIFD - D:/output/IMG20151215232746.jpg
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mattwilson1024** [comment]
This error is not coming from `google-photos-exif` itself, it is originating from [https://exiftool.org/](ExifTool), which is the library used to read & write EXIF metadata in the JPEG file (specifically, this project uses this dependency: [exiftool-vendored](https://www.npmjs.com/package/exiftool-vendored).

I'm not able to reproduce the error myself because I didn't encounter it for any of my images. If it helps though, this thread on the ExifTool forum looks relevant: [https://exiftool.org/forum/index.php?topic=4764.0](https://exiftool.org/forum/index.php?topic=4764.0).

It looks like the error you posted can occur if the JPEG contains metadata that is corrupted or has errors. [FAQ #20](https://exiftool.org/faq.html#Q20) lists a command which might be worth a go.
